from apps.contas.permissions import (  # noqa: F401
    HIERARQUIA,
    HasPermissaoPortal,
    IsAdmin,
    IsAssessoria,
    IsAuthenticatedMarryMe,
    IsCS,
    IsSDR,
    IsEquipe,
    IsEquipeOuPortalVinculado,
    IsPortalUsuario,
    IsPrestador,
    get_vinculo_ativo,
    tem_role_minimo,
    usuario_tem_permissao_portal,
)
