# Generated by Django 6.0.5 on 2026-05-21 17:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prestadores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_calculo', models.DateField()),
                ('score', models.IntegerField()),
                ('status', models.CharField(choices=[('saudavel', 'Saudável'), ('atencao', 'Atenção'), ('em_risco', 'Em Risco')], max_length=20)),
                ('score_cpl', models.IntegerField()),
                ('score_orcamento', models.IntegerField()),
                ('score_leads', models.IntegerField()),
                ('score_ctr', models.IntegerField()),
                ('cpl_real', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('gasto_real', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('leads_real', models.IntegerField(null=True)),
                ('roi', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('prestador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_scores', to='prestadores.prestador')),
            ],
            options={
                'verbose_name': 'Health Score',
                'verbose_name_plural': 'Health Scores',
                'ordering': ['-data_calculo'],
            },
        ),
        migrations.CreateModel(
            name='MetricaMeta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_referencia', models.DateField()),
                ('campanha_id', models.CharField(max_length=100)),
                ('campanha_nome', models.CharField(max_length=200)),
                ('impressoes', models.IntegerField(default=0)),
                ('alcance', models.IntegerField(default=0)),
                ('cliques', models.IntegerField(default=0)),
                ('ctr', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('leads', models.IntegerField(default=0)),
                ('gasto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cpl', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('prestador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metricas', to='prestadores.prestador')),
            ],
            options={
                'verbose_name': 'Métrica Meta',
                'verbose_name_plural': 'Métricas Meta',
                'ordering': ['-data_referencia'],
            },
        ),
        migrations.CreateModel(
            name='RelatorioIA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('periodo_inicio', models.DateField()),
                ('periodo_fim', models.DateField()),
                ('dados_json', models.JSONField()),
                ('health_score', models.IntegerField(null=True)),
                ('tokens_usados', models.IntegerField(default=0)),
                ('gerado_em', models.DateTimeField(auto_now_add=True)),
                ('prestador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios', to='prestadores.prestador')),
            ],
            options={
                'verbose_name': 'Relatório IA',
                'verbose_name_plural': 'Relatórios IA',
                'ordering': ['-gerado_em'],
            },
        ),
    ]
