# Generated by Django 6.0.5 on 2026-05-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=100, unique=True)),
                ('valor', models.TextField()),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração Meta',
                'verbose_name_plural': 'Configurações Meta',
            },
        ),
    ]
