# Generated by Django 6.0.5 on 2026-06-16 18:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prestadores', '0004_alter_usuario_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConviteAcesso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('tipo', models.CharField(choices=[('titular', 'Titular'), ('assessoria', 'Assessoria')], max_length=20)),
                ('permissoes_portal', models.JSONField(blank=True, default=dict)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('usado', 'Usado'), ('expirado', 'Expirado'), ('revogado', 'Revogado')], default='pendente', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('expira_em', models.DateTimeField()),
                ('usado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='convites_emitidos', to=settings.AUTH_USER_MODEL)),
                ('prestador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convites', to='prestadores.prestador')),
                ('usuario_criado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='convites_aceitos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Convite de Acesso',
                'verbose_name_plural': 'Convites de Acesso',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='VinculoPrestador',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('titular', 'Titular'), ('assessoria', 'Assessoria')], max_length=20)),
                ('permissoes_portal', models.JSONField(blank=True, default=dict)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('prestador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros', to='prestadores.prestador')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_prestador', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vínculo com Prestador',
                'verbose_name_plural': 'Vínculos com Prestador',
                'unique_together': {('usuario', 'prestador')},
            },
        ),
    ]
