# Generated by Django 6.0.5 on 2026-05-21 17:27

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('cs', 'CS'), ('sdr', 'SDR'), ('dev', 'Dev')], default='cs', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='usuario_set', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='usuario_permission_set', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Prestador',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_artistico', models.CharField(max_length=200)),
                ('nome_completo', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('musico', 'Músico / Banda'), ('fotografo', 'Fotógrafo / Videomaker'), ('celebrante', 'Celebrante'), ('dj', 'DJ'), ('cerimonialista', 'Cerimonialista')], max_length=20)),
                ('fase', models.CharField(choices=[('onboarding', 'Onboarding'), ('planejamento', 'Planejamento de Metas'), ('growth', 'Growth'), ('voo_cruzeiro', 'Voo de Cruzeiro'), ('renovacao', 'Renovação'), ('pausado', 'Pausado'), ('churn', 'Churn')], default='onboarding', max_length=20)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('whatsapp', models.CharField(max_length=20)),
                ('instagram', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('meta_ad_account_id', models.CharField(blank=True, max_length=50)),
                ('meta_cpl_alvo', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('meta_orcamento_mensal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('meta_leads_alvo_mensal', models.IntegerField(blank=True, null=True)),
                ('ticket_medio_estimado', models.DecimalField(decimal_places=2, default=3000, max_digits=10)),
                ('health_score', models.IntegerField(blank=True, null=True)),
                ('health_status', models.CharField(blank=True, max_length=20, null=True)),
                ('meta_ultima_sync', models.DateTimeField(blank=True, null=True)),
                ('dados_entrevista', models.JSONField(default=dict)),
                ('analise_estrategica', models.JSONField(default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestadores', to='prestadores.usuario')),
            ],
            options={
                'verbose_name': 'Prestador',
                'verbose_name_plural': 'Prestadores',
                'ordering': ['-atualizado_em'],
            },
        ),
    ]
