# Generated by Django 6.0.5 on 2026-05-29 10:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestadores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenPrimeiroAcesso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('usado', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('expira_em', models.DateTimeField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens_acesso', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token de Primeiro Acesso',
                'verbose_name_plural': 'Tokens de Primeiro Acesso',
            },
        ),
    ]
