# Generated by Django 6.0.5 on 2026-05-29 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestadores', '0002_tokenprimeiroacesso'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='prestador_vinculado',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_acesso', to='prestadores.prestador'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('cs', 'CS'), ('sdr', 'SDR'), ('dev', 'Dev'), ('prestador', 'Prestador')], default='cs', max_length=20),
        ),
    ]
