# Generated by Django 6.0.5 on 2026-06-16 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestadores', '0003_usuario_prestador_vinculado_alter_usuario_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('cs', 'CS'), ('sdr', 'SDR'), ('dev', 'Dev'), ('prestador', 'Prestador'), ('assessoria', 'Assessoria')], default='cs', max_length=20),
        ),
    ]
