# Generated by Django 6.0.5 on 2026-06-16 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestadores', '0004_alter_usuario_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='prestador_vinculado',
        ),
        migrations.DeleteModel(
            name='TokenPrimeiroAcesso',
        ),
    ]
