FROM python:3.12-alpine

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

RUN apk add --no-cache bash

COPY requirements/base.txt .
RUN pip install --no-cache-dir -r base.txt

COPY . .

COPY docker/celery-entrypoint.sh /celery-entrypoint.sh
RUN chmod +x /celery-entrypoint.sh
