# Generated by Django 6.0.5 on 2026-05-21 17:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prestadores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSessao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(default='Nova conversa', max_length=200)),
                ('tipo', models.CharField(choices=[('geral', 'Geral'), ('video', 'Vídeo de Apresentação'), ('cta', 'CTA / Anúncio'), ('direcao', 'Direção Criativa'), ('analise', 'Análise Estratégica')], default='geral', max_length=20)),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('finalizada', 'Finalizada'), ('arquivada', 'Arquivada')], default='ativa', max_length=20)),
                ('roteiro_final', models.JSONField(blank=True, null=True)),
                ('tokens_usados', models.IntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('prestador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes_chat', to='prestadores.prestador')),
            ],
            options={
                'verbose_name': 'Sessão de Chat',
                'verbose_name_plural': 'Sessões de Chat',
                'ordering': ['-atualizado_em'],
            },
        ),
        migrations.CreateModel(
            name='ChatMensagem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'Usuário'), ('assistant', 'Assistente')], max_length=20)),
                ('content', models.TextField()),
                ('arquivos', models.JSONField(default=list)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='roteiros.chatsessao')),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
                'ordering': ['criado_em'],
            },
        ),
        migrations.CreateModel(
            name='RoteiroFinal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('video', 'Vídeo de Apresentação'), ('cta', 'CTA / Anúncio'), ('direcao', 'Direção Criativa'), ('analise', 'Análise Estratégica')], max_length=20)),
                ('conteudo_json', models.JSONField()),
                ('aprovado', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('prestador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roteiros', to='prestadores.prestador')),
                ('sessao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roteiros', to='roteiros.chatsessao')),
            ],
            options={
                'verbose_name': 'Roteiro Final',
                'verbose_name_plural': 'Roteiros Finais',
                'ordering': ['-criado_em'],
            },
        ),
    ]
